[package]
name = "sha2-host"
version = "1.0.0"
edition = "2024"
default-run = "sha2-host"
publish = false

[[bin]]
name = "vkey"
path = "bin/vkey.rs"

[dependencies]
alloy-sol-types = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
hex = { workspace = true }
sha2 = { git = "https://github.com/ziren-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-0.10.8" }
serde_json = { workspace = true }
serde = { workspace = true }
sha2-lib = { path = "../lib", features = ["host"] }
zkm-sdk = { workspace = true }
rkyv = { version = "0.7.45", features = ["std", "validation"] }

[build-dependencies]
zkm-build = { workspace = true }