[package]
name = "aggregation-host"
version = "1.0.0"
edition = "2024"
publish = false

[dependencies]
alloy-sol-types = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
aggregation-lib = { path = "../lib" }
rkyv = { version = "0.7.45", features = ["std", "validation", "alloc"] }
sha2 = { git = "https://github.com/ziren-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-0.10.8" }
zkm-sdk = { workspace = true }

[build-dependencies]
zkm-build = { workspace = true }

[[bin]]
name = "aggregation"
path = "src/main.rs"

[[bin]]
name = "evm"
path = "bin/evm.rs"

[[bin]]
name = "vkey"
path = "bin/vkey.rs"