[package]
name = "keccak-script"
version = { workspace = true }
edition = { workspace = true }
default-run = "keccak-script"
publish = false

[dependencies]
rkyv = { version = "0.7.45", features = ["std", "validation", "alloc"] }
rkyv_derive = { version = "0.7.45" }
hex = { workspace = true }
tiny-keccak = { workspace = true }
sp1-sdk = { workspace = true }
common = {workspace = true}

[build-dependencies]
sp1-build = "5.0.8"


[[bin]]
name = "keccak-script"
path = "src/main.rs"