[package]
name = "sha3-host"
version = "1.0.0"
edition = "2024"
publish = false

# [[bin]]
# name = "evm"
# path = "bin/evm.rs"

# [[bin]]
# name = "vkey"
# path = "bin/vkey.rs"

[dependencies]
alloy-sol-types = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
sha3-lib = { path = "../lib", features = ["host"] }
zkm-sdk = { workspace = true }
rkyv = { version = "0.7.45", features = ["std", "validation"] }
bincode = "1.3"

[build-dependencies]
zkm-build = { workspace = true }
