[package]
name = "merkle-script"
version = { workspace = true }
edition = { workspace = true }
default-run = "merkle-script"
publish = false

[dependencies]
rkyv = { version = "0.7.45", features = ["std", "validation"] }
hex = { workspace = true }
sp1-sdk = { workspace = true }
common = { workspace = true }

coset-bls12_381 = { workspace = true }
plonk = { workspace = true, features = ["std"] }
poseidon-merkle = { path = "../../../3-Plonk/poseidon-merkle", package = "poseidon-merkle", features = ["zk"] }
coset-bytes = { workspace = true }
bincode = "1.3.3"
rand = "0.8.5"

[build-dependencies]
sp1-build = "5.0.8"

[[bin]]
name = "merkle-script"
path = "src/main.rs"