[package]
name = "aggregation-host"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
zkm-sdk = { workspace = true }
tracing = { workspace = true }
common = { path = "/opt/project/1-Sender/common" }
fibonacci-add-lib = { path = "../../fibonacci_add/lib", features = ["host"] }
fibonacci-mul-lib = { path = "../../fibonacci_mul/lib", features = ["host"] }
sha2-lib = { path = "../../sha2/lib", features = ["host"] }
sha3-lib = { path = "../../sha3/lib", features = ["host"] }
rkyv = { version = "0.7.45", features = ["std", "validation"] }
hex = "0.4.3"
clap = { version = "4.4.0", features = ["derive"] }

[build-dependencies]
zkm-build = { workspace = true }