[package]
name = "sha3"
version = "0.1.0"
edition = "2024"

[dependencies]
sha3 = { git = "https://github.com/ziren-patches/RustCrypto-hashes", package = "sha3" }
clap = { version = "4.4.8", features = ["derive"] }
hex = "0.4.3"
rkyv = { version = "0.7.45", features = ["std", "validation", "alloc"] }
rkyv_derive = { version = "0.7.45" }
common = {path="../common"}

[[bin]]
name = "sha3_batch"
path = "src/main_batch.rs"