[workspace]
members = [
  "aggregation/guest",
  "aggregation/host",
  "coset/guest",
  "coset/host",
  "coset/lib",
  "ecdsa/guest",
  "ecdsa/host",
  "ecdsa/lib",
  "fibonacci_add/guest",
  "fibonacci_add/host",
  "fibonacci_add/lib",
  "fibonacci_mul/guest",
  "fibonacci_mul/host",
  "fibonacci_mul/lib",
  "keccak/guest",
  "keccak/host",
  "keccak/lib",
  "schnorr/guest",
  "schnorr/host",
  "schnorr/lib",
  "rsa/guest",
  "rsa/host",
  "rsa/lib",
  "merkle/guest",
  "merkle/host",
  "merkle/lib",
  "sha2/guest",
  "sha2/host",
  "sha2/lib",
  "sha3/guest",
  "sha3/host",
  "sha3/lib"
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = { version = "1.5.2" }
alloy-primitives = { version = "1.0", default-features = false, features = [
    "rlp",
] }
clap = { version = "4.0", features = ["derive", "env"] }
dotenv = "0.15.0"
hex = "0.4.3"
serde_json = { version = "1.0.132", default-features = false, features = ["alloc"] }
#serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde = "1.0.204"
tracing = "0.1.40"

coset-bls12_381 = { path = "../3-Plonk/coset-bls12_381" }
coset-poseidon = { path = "../3-Plonk/coset-poseidon" }
coset-bytes = { path = "../3-Plonk/coset-bytes/bytes" }
plonk = { path = "../3-Plonk/plonk" }
poseidon-merkle = { path = "../3-Plonk/poseidon-merkle" }
merkle = { path = "../3-Plonk/coset-merkle", package = "coset-merkle" }

zkm-sdk = { git = "https://github.com/zkMIPS/zkMIPS.git" }
zkm-zkvm = { git = "https://github.com/zkMIPS/zkMIPS.git" }
zkm-build = { git = "https://github.com/zkMIPS/zkMIPS.git" }

#zkm-sdk = { git = "https://github.com/ProjectZKM/Ziren.git" }
#zkm-zkvm = { git = "https://github.com/ProjectZKM/Ziren.git" }
#zkm-build = { git = "https://github.com/ProjectZKM/Ziren.git" }