[package]
name = "keccak-host"
version = "1.0.0"
edition = "2024"
publish = false

[dependencies]
alloy-sol-types = { workspace = true }
clap = { workspace = true }
dotenv = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
keccak-lib = { path = "../lib", features = ["host"] }
common = { path = "/opt/project/1-Sender/common" }
rkyv = { version = "0.7.45", features = ["std", "validation", "alloc"] }
tiny-keccak = { version = "2.0", features = ["keccak"] }
zkm-sdk = { workspace = true }

[build-dependencies]
zkm-build = { workspace = true }

[[bin]]
name = "keccak"
path = "src/main.rs"