[package]
version = "0.1.0"
name = "poseidon-merkle-script" 
edition = "2021"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"


[dependencies]
sp1-sdk = "5.0.8"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
rkyv = { version = "0.7.45", features = ["std", "validation", "alloc"] }
bytecheck = "0.6.12"
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
coset-lib = { path = "../lib" }
dotenv = "0.15.0"
rand = "0.8.5"  # 添加随机数生成库依赖
coset-bls12_381 = { workspace = true }
coset-poseidon = { workspace = true }
plonk = { workspace = true , features = ["std"] }
poseidon-merkle = {  workspace = true , features = ["zk"] }
alloy-sol-types = { workspace = true }
blake3 = "1.5.1"
chrono = "0.4.38"
coset-bytes = { workspace = true }
merkle = {workspace = true}
common = {workspace = true}


[build-dependencies]
sp1-build = "5.0.8"