[package]
name = "fibonacci-mul-host"
version = "1.0.0"
edition = "2024"
publish = false

[dependencies]
alloy-sol-types = { workspace = true }
alloy-primitives = "0.5"
clap = { workspace = true }
dotenv = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
fibonacci-mul-lib = { path = "../lib", features = ["host"] }
common = { path = "/opt/project/1-Sender/common" }
rkyv = { version = "0.7.45", features = ["std", "validation"] }
zkm-sdk = { workspace = true }

[build-dependencies]
zkm-build = { workspace = true }

[[bin]]
name = "fibonacci-mul"
path = "src/main.rs"

exclude = ["build"]