[workspace]
members = [
    "coset/lib",
    "coset/program",
    "coset/script",
    "fibonacci_add/program",
    "fibonacci_add/script",
    "sha2/program",
    "sha2/script",
    "aggregation/program",
    "aggregation/script",
    "keccak/program",
    "keccak/script",
    "rsa/program",
    "rsa/script",
    "sha3/program",
    "sha3/script",
    "ecdsa/program",
    "ecdsa/script",
    "schnorr/program",
    "schnorr/script",
    "fibonacci_mul/program",
    "fibonacci_mul/script",
    "merkle/program",
    "merkle/script",
]
resolver = "2"

[workspace.package]
version = "1.1.0"
edition = "2024"

[workspace.dependencies]
alloy-sol-types = "0.6.1"
sp1-sdk = "5.0.8"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
dotenv = "0.15.0"
rand = "0.8.5"  # 添加随机数生成库依赖
coset-bls12_381 = { path = "../3-Plonk/coset-bls12_381", package = "coset-bls12_381" }
coset-poseidon = { path = "../3-Plonk/coset-poseidon", package = "coset-poseidon" }
plonk = { path = "../3-Plonk/plonk", package = "plonk", features = ["std"] }
poseidon-merkle = { path = "../3-Plonk/poseidon-merkle", package = "poseidon-merkle", features = ["zk"] }
coset-bytes = { path = "../3-Plonk/coset-bytes/bytes", package = "coset-bytes" }
blake3 = "1.5.1"
chrono = "0.4.38"
merkle = { path = "../1-Sender/merkle" }
sp1-zkvm = "5.0.8"
common = {path = "../1-Sender/common"}
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", tag = "patch-2.0.2-sp1-4.0.0" }

[patch.crates-io]
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.8-sp1-4.0.0" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", tag = "patch-2.0.2-sp1-4.0.0" }