[package]
name = "mips-verify"
version = "1.0.0"
edition = "2024"
default-run = "mips-verify"
publish = false

[[bin]]
name = "mips-verify"
path = "src/main.rs"

[dependencies]
hex = "^0.4.3"
serde_json = "^1.0.85"
serde = { version = "^1.0.147", features = ["derive"] }
plonk = { path = "/opt/project/3-Plonk/plonk", features = ["std"] }
coset-bytes = { path = "/opt/project/3-Plonk/coset-bytes/bytes", package = "coset-bytes" }
coset-bls12_381 = { path = "/opt/project/3-Plonk/coset-bls12_381", package = "coset-bls12_381", features = ["groups", "pairings"] }
coset-jubjub = { path = "/opt/project/3-Plonk/coset-jubjub", package = "coset-jubjub" }
merlin = "3.0"
rand_core = "0.6"
ff = "0.13"
itertools = "0.9"
hashbrown = { version = "0.9", features = ["ahash"] }