[package]
name = "schnorr-script"
version = { workspace = true }
edition = { workspace = true }
default-run = "schnorr-script"
publish = false

[dependencies]
rkyv = { version = "0.7.45", features = ["std", "validation"] }
hex = { workspace = true }
sp1-sdk = { workspace = true }
common = { workspace = true }

[build-dependencies]
sp1-build = "5.0.8"


[[bin]]
name = "schnorr-script"
path = "src/main.rs"