[package]
name = "coset-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
coset-bls12_381 = { workspace = true }
coset-poseidon = { workspace = true }
plonk = { workspace = true , features = ["std"] }
poseidon-merkle = {  workspace = true , features = ["zk"] }
alloy-sol-types = { workspace = true }
rand = "0.8.5"
bincode = { version = "1.3.3", optional = true }
zkm-sdk = { git = "https://github.com/zkMIPS/zkMIPS.git", optional = true }

[features]
host = ["bincode", "zkm-sdk"]