[package]
name = "schnorr-host"
version = "1.0.0"
edition = "2024"
publish = false

default-run = "schnorr-host"

[dependencies]
alloy-sol-types = "1.5.2"
clap = { version = "4.0", features = ["derive", "env"] }
dotenv = "0.15.0"
hex = "0.4.3"
serde_json = { version = "1.0.132", default-features = false, features = ["alloc"] }
serde = "1.0.204"
rkyv = { version = "0.7.45", features = ["std", "validation"] }
schnorr-lib = { path = "../lib", features = ["host"] }
zkm-sdk = { git = "https://github.com/zkMIPS/zkMIPS.git" }

[build-dependencies]
zkm-build = { workspace = true }