[package]
version = "0.1.0"
name = "coset"
edition = "2021"

[dependencies]
alloy-sol-types.workspace = true
alloy-primitives.workspace = true
coset-lib = { path = "../lib" } 
coset-bls12_381.workspace = true
coset-poseidon.workspace = true
coset-bytes.workspace = true
plonk.workspace = true
poseidon-merkle.workspace = true
rand = "0.8.5"
merkle.workspace = true
zkm-zkvm.workspace = true